misc fixes

diff --git a/prepvideos b/prepvideos
--- a/prepvideos
+++ b/prepvideos
@@ -1,6 +1,9 @@
 #!/bin/sh
 set -e
 
+DONT=""
+TIMESTAMP_ONLY=""
+
 gififyIfLivePic() {
 	local readonly file="${1}"
 	local duration
@@ -16,13 +19,13 @@ gififyIfLivePic() {
 	duration=$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 -i "${file}" | awk -F. '{print $1}')
 
 	if [ "${duration}" -gt 10 ]; then
-		echo "==> Not going to gifify '${file}'."
+		echo "==> Not going to gifify ${duration}s long '${file}'."
 		return 1
 	fi
 
-	scale=$(ffprobe -v error -select_streams v:0 -show_entries stream=width,height -of csv=s=x:p=0 -i "${file}" | sed -e 's/x/\//' | bc -l)
+	scale=$(ffprobe -v error -select_streams v:0 -show_entries stream=width,height -of csv=s=x:p=0 -i "${file}" | sed -e 's/x/\//' -e 's/x$//' | head -1 | bc -l)
 
-	rotation=$(ffprobe -loglevel error -select_streams v:0 -show_entries stream_tags=rotate -of default=nw=1:nk=1 -i "${file}")
+	rotation=$(ffprobe -v error -select_streams v:0 -show_entries stream -of default=noprint_wrappers=1 -i "${file}" | sed -n -e 's/^rotation=-*//p')
 
 	if [ x"${rotation}" = x"90" ]; then
 		v="${h}"
@@ -34,18 +37,103 @@ gififyIfLivePic() {
 
 
 	echo "==> Turning '${file}' into a gif..."
-	livegif "${file}" "${orientation}" "${h}x${v}"
-	mv "${file}" .livepics
+	${DONT} livegif "${file}" "${orientation}" "${h}x${v}"
+	${DONT} mv "${file}" .livepics
 
 	return 0
 }
+
+createScreenshot() {
+	file="${1}"
+	jpg="${jpg}"
+	echo "==> Grabbing screenshot from ${file}..."
+	${DONT} ffmpeg -loglevel error -i ${file} -an -ss 00:00:01 -an -r 1 -vframes 1 -y %d.jpg 2>/dev/null
+	${DONT} mv 1.jpg ${jpg}
+}
+
+resizeMovie() {
+	file="${1}"
+	prefix="${2}"
+
+	echo "==> Resizing ${file}..."
+	${DONT} mv ${file} 1.MOV
+	#${DONT} ffmpeg -i 1.MOV -c:a copy -vf scale=iw/2:-1 0.MOV
+	${DONT} ffmpeg -loglevel error -i 1.MOV -c:a copy -vf scale=640:-1 -vcodec libtheora -acodec libvorbis -qscale:v 8 -qscale:a 8 -max_muxing_queue_size 9999 small.ogv
+	${DONT} mv small.ogv ${prefix}-small.ogv
+	${DONT} mv 1.MOV ${file}
+}
+
+renameByDate() {
+	file="${1}"
+	prefix="${2}"
+	jpg="${3}"
+
+	suffix="${file##*.}"
+	date=$(strings ${file} | egrep "^[0-9][0-9][0-9][0-9]-[0-9][0-9]" | tail -1)
+	if [ -z "${date}" ]; then
+		echo "Unable to add date to ${jpg} - run exiftool yourself."
+	else
+		echo "==> Adding a date ${date} to ${jpg}..."
+		${DONT} exiftool -P -CreateDate="${date}" ${jpg} 2>/dev/null
+		date="$( echo "${date}" | sed -e 's/:/-/g' -e 's/[+-][0-9][0-9][0-9][0-9]//' )"
+		${DONT} mv ${file} ${date}.${suffix}
+		${DONT} mv ${prefix}-small.ogv ${date}-small.ogv
+		${DONT} mv ${jpg} ${date}.jpg
+		${DONT} rm ${jpg}_original
+	fi
+}
+
+
+handleMp4() {
+	file="${1}"
+
+	if [ ! -e ${file} ]; then
+		continue
+	fi
+	echo "=> Preparing ${file}..."
+	prefix="${file%%.mp4}"
+	jpg=${prefix}.jpg
+	${DONT} ffmpeg -i ${file} -an -ss 00:00:01 -an -r 1 -vframes 1 -y %d.jpg
+	${DONT} mv 1.jpg ${jpg}
+	${DONT} ffmpeg -i ${file} -vcodec libtheora -acodec libvorbis -qscale:v 10 -qscale:a 10 ${prefix}.ogv
+	${DONT} ~/bin/adddate ${file} ${jpg}
+}
+
+usage() {
+	cat <<EOH
+Usage: ${PROGNAME} [-dht]
+        -d  don't do anything; just echo what would be done
+        -h  print this help and exit
+        -t  timestamp files only
+EOH
+}
+
+while getopts 'dht' opt; do
+	case "${opt}" in
+		d)
+			DONT="echo "
+			;;
+		h|\?)
+			usage
+			exit 0
+			# NOTREACHED
+			;;
+		t)
+			TIMESTAMP_ONLY="yes"
+			;;
+		*)
+			usage
+			exit 1
+			# NOTREACHED
+	esac
+done
 
 #for file in *.m4v *mov *MOV; do
 #for file in *MOV; do
 
 mkdir -p .livepics
 
-for file in `ls *mov *MOV | grep -v -- -`; do
+for file in $(ls *mov *MOV | grep -v -- -); do
 	if [ ! -e "${file}" ]; then
 		continue
 	fi
@@ -58,44 +146,16 @@ for file in `ls *mov *MOV | grep -v -- -`; do
 	prefix="${file%%.MOV}"
 	prefix="${prefix%%.mov}"
 	prefix="${prefix%%.m4v}"
-	suffix="${file##*.}"
 	jpg=${prefix}.jpg
-	echo "==> Grabbing screenshot from ${file}..."
-	ffmpeg -loglevel error -i ${file} -an -ss 00:00:01 -an -r 1 -vframes 1 -y %d.jpg 2>/dev/null
-	mv 1.jpg ${jpg}
-	mv ${file} 1.MOV
-	#ffmpeg -i 1.MOV -c:a copy -vf scale=iw/2:-1 0.MOV
-	echo "==> Resizing ${file}..."
-	ffmpeg -loglevel error -i 1.MOV -c:a copy -vf scale=640:-1 -vcodec libtheora -acodec libvorbis -qscale:v 8 -qscale:a 8 small.ogv
-	mv small.ogv ${prefix}-small.ogv
-	mv 1.MOV ${file}
 
-	date=$(strings ${file} | egrep "^[0-9][0-9][0-9][0-9]-[0-9][0-9]" | tail -1)
-	if [ -z "${date}" ]; then
-		echo "Unable to add date to ${jpg} - run exiftool yourself."
-	else
-		echo "==> Adding a date ${date} to ${jpg}..."
-		exiftool -P -CreateDate="${date}" ${jpg} 2>/dev/null
-		date="$( echo "${date}" | sed -e 's/:/-/g' -e 's/[+-][0-9][0-9][0-9][0-9]//' )"
-		mv ${file} ${date}.${suffix}
-		mv ${prefix}-small.ogv ${date}-small.ogv
-		mv ${jpg} ${date}.jpg
-		rm ${jpg}_original
-	fi
+	createScreenshot "${file}" "${jpg}"
+	resizeMovie "${file}" "${prefix}"
+	renameByDate "${file}" "${prefix}" "${jpg}"
 
 	#convert -rotate 180 ${jpg} 1.jpg && mv 1.jpg ${jpg}
 done
 
 # mp4 are vine's, so short and small
 for file in *.mp4; do
-	if [ ! -e ${file} ]; then
-		continue
-	fi
-	echo "=> Preparing ${file}..."
-	prefix="${file%%.mp4}"
-	jpg=${prefix}.jpg
-	ffmpeg -i ${file} -an -ss 00:00:01 -an -r 1 -vframes 1 -y %d.jpg
-	mv 1.jpg ${jpg}
-	ffmpeg -i ${file} -vcodec libtheora -acodec libvorbis -qscale:v 10 -qscale:a 10 ${prefix}.ogv
-	~/bin/adddate ${file} ${jpg}
+	handleMp4 "${file}"
 done
